### ISSUE TITLE
recognise the - [ ] and - [x] of GFM

### ISSUE THREAD

**Issue by bquast** [metacran/readme-builder-app#1]
see e.g. bij todo list here

http://www.r-pkg.org/pkg/gvc

this should be like:
- [ ] rei
- [ ] vax

and 
- [x] rei
- [x] vax

**Comment by gaborcsardi** [comment]
Yeah, I'll switch to GitHub's API to build READMEs and NEWS files, and then it should all look the same as on GitHub.

**Comment by gaborcsardi** [comment]
See #2.
